paths:
  /health-check:
    get:
      description: Check if the service is up and running
      operationId: health-check
      responses:
        "200":
          description: Search service is up and running
        "404":
          description: Not found
  /persons:
    post:
      consumes:
      - application/json
      description: Index one or many Persons
      operationId: post-persons
      parameters:
      - in: body
        name: body
        required: true
        schema:
          properties:
            persons:
              items:
                properties:
                  addressLine1:
                    type: string
                  addressLine2:
                    type: string
                  addressLine3:
                    type: string
                  addresses:
                    items:
                      properties:
                        addressLines:
                          items:
                            type: string
                          type: array
                        className:
                          type: string
                        postcode:
                          type: string
                      type: object
                    type: array
                  caseRecNumber:
                    type: string
                  cases:
                    items:
                      properties:
                        batchId:
                          type: string
                        caseRecNumber:
                          type: string
                        className:
                          type: string
                        normalizedUid:
                          format: int64
                          type: integer
                        uId:
                          type: string
                      type: object
                    type: array
                  className:
                    type: string
                  companyName:
                    type: string
                  country:
                    type: string
                  county:
                    type: string
                  dob:
                    type: string
                  email:
                    type: string
                  firstname:
                    type: string
                  homePhoneNumber:
                    properties:
                      className:
                        type: string
                      default:
                        type: boolean
                      id:
                        format: int32
                        type: integer
                      phoneNumber:
                        type: string
                      type:
                        type: string
                    type: object
                  id:
                    format: int64
                    type: integer
                  isAirmailRequired:
                    type: boolean
                  middlenames:
                    type: string
                  mobilePhoneNumber:
                    properties:
                      className:
                        type: string
                      default:
                        type: boolean
                      id:
                        format: int32
                        type: integer
                      phoneNumber:
                        type: string
                      type:
                        type: string
                    type: object
                  normalizedUid:
                    format: int64
                    type: integer
                  orders:
                    items:
                      properties:
                        className:
                          type: string
                        order:
                          properties:
                            batchId:
                              type: string
                            caseRecNumber:
                              type: string
                            className:
                              type: string
                            normalizedUid:
                              format: int64
                              type: integer
                            uId:
                              type: string
                          type: object
                      type: object
                    type: array
                  personType:
                    type: string
                  phoneNumber:
                    type: string
                  phoneNumbers:
                    items:
                      properties:
                        className:
                          type: string
                        default:
                          type: boolean
                        id:
                          format: int32
                          type: integer
                        phoneNumber:
                          type: string
                        type:
                          type: string
                      type: object
                    type: array
                  postcode:
                    type: string
                  sageId:
                    type: string
                  surname:
                    type: string
                  town:
                    type: string
                  uId:
                    type: string
                  workPhoneNumber:
                    properties:
                      className:
                        type: string
                      default:
                        type: boolean
                      id:
                        format: int32
                        type: integer
                      phoneNumber:
                        type: string
                      type:
                        type: string
                    type: object
                type: object
              type: array
          type: object
      produces:
      - application/json
      responses:
        "202":
          description: The request has been handled and individual index responses are included in the response body
          schema:
            properties:
              results:
                items:
                  properties:
                    id:
                      format: int64
                      type: integer
                    message:
                      type: string
                    statusCode:
                      type: integer
                  type: object
                type: array
            type: object
        "400":
          description: Request failed validation
          schema:
            properties:
              errors:
                items:
                  properties:
                    description:
                      type: string
                    name:
                      type: string
                  type: object
                type: array
              message:
                type: string
            type: object
        "404":
          description: Not found
        "500":
          description: Unexpected error occurred
swagger: "2.0"
