version: 2.1

workflows:
  pr-build-and-test:
    jobs:
      - test_search_service:
          name: test_search_service
      - gosec_search_service:
          name: gosec_search_service
      - build_search_service:
          name: build_search_service
          requires: [test_search_service,gosec_search_service]

orbs:
  search_service:
    commands:
      install_aws_cli:
        steps:
          - run:
              name: Install AWS CLI
              command: sudo pip3 install awscli --upgrade
      install_aws_local_wrapper:
        steps:
          - run:
              name: Install AWS Local Wrapper
              command: sudo pip3 install awscli-local --upgrade
      ecr_login:
        steps:
          - run:
              name: Login to ECR
              command: |
                temp_role=$(aws sts assume-role --role-arn arn:aws:iam::311462405659:role/sirius-ci --role-session-name ci)
                export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq .Credentials.AccessKeyId | xargs)
                export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq .Credentials.SecretAccessKey | xargs)
                export AWS_SESSION_TOKEN=$(echo $temp_role | jq .Credentials.SessionToken | xargs)
                eval $(aws ecr get-login --no-include-email --region=eu-west-1)
      test_localstack_setup:
        steps:
          - run:
              name: Localstack ES Setup
              command: |
                cd scripts/localstack
                chmod +x localstack_init.sh
                ./localstack_init.sh
    executors:
      python:
        docker: [image: circleci/python]

jobs:
  test_search_service:
    docker:
      - image: circleci/golang
        environment:
          TEST_RESULTS: /tmp/test-results
          GOTESTSUM_FORMAT: short-verbose
          AWS_ACCESS_KEY_ID: localstack
          AWS_SECRET_ACCESS_KEY: localstack
          DEFAULT_REGION: eu-west-1
          AWS_ELASTICSEARCH_ENDPOINT: http://localhost:4571
          SECRETS_MANAGER_ENDPOINT: http://localhost:4566
      - image: localstack/localstack-full:0.12.8
        environment:
          DEFAULT_REGION: eu-west-1
          SERVICES: es,secretsmanager
    steps:
      - checkout
      - run:
          name: Install PiP
          command: |
            sudo apt update
            sudo apt install python3-venv python3-pip
      - search_service/install_aws_cli
      - search_service/install_aws_local_wrapper
      - search_service/test_localstack_setup
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for ES
          command: dockerize -wait tcp://localhost:4571 -timeout 1m
      - run:
          name: Install Go Modules Dependencies
          command: go mod download
      - run: mkdir -p $TEST_RESULTS
      - run:
          name: Run Unit and Intergration Tests
          command: gotestsum --junitfile unit-tests.xml
      - store_test_results:
          path: /tmp/test-results

  gosec_search_service:
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - run: |
          wget -O - -q https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s v2.7.0
          ./bin/gosec ./...

  build_search_service:
    executor: search_service/python
    parameters:
      container_repo_url:
        type: string
        default: 311462405659.dkr.ecr.eu-west-1.amazonaws.com/search_service
    steps:
      - checkout
      - search_service/install_aws_cli
      - setup_remote_docker:
          version: 18.06.0-ce
          docker_layer_caching: false
      - run:
          name: Build
          command: |
            docker build --file Dockerfile --tag search_service:latest .
      - search_service/ecr_login
      - run:
          name: Push container
          command: |
            export SHORT_HASH=${CIRCLE_SHA1:0:7} >> $BASH_ENV
            docker tag search_service:latest << parameters.container_repo_url >>:latest
            docker tag search_service:latest << parameters.container_repo_url >>:$CIRCLE_BRANCH-$SHORT_HASH
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              # We want all of the tags pushed
              docker push << parameters.container_repo_url >>
            else
              docker push << parameters.container_repo_url >>:$CIRCLE_BRANCH-$SHORT_HASH
            fi
